name: Publish

on:
  release:
    types: [prereleased]
    branches:
      - main

jobs:
  publish:
    name: Deploy & Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Export package version
        run: echo "PACKAGE_VERSION=$(cat package.json | jq '.version' | sed -e 's/"//g')" >> $GITHUB_ENV

      - name: Check release version
        if: ${{ github.event.release.tag_name != env.PACKAGE_VERSION }}
        run: echo "Release tag does not match package version. Please update package.json." && exit 1

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
